api:
  statcast: https://baseballsavant.mlb.com/statcast_search/csv?all=true&hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=&hfC=&hfSea={year}%7C&hfSit=&player_type=pitcher&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=&game_date_lt=&team={team}&position=&hfRO=&home_road=&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name-event&sort_col=pitches&player_event_sort=api_p_release_speed&sort_order=desc&min_abs=0&type=details&
  players: https://docs.google.com/spreadsheets/d/1JgczhD5VDQ1EiXqVG-blttZcVwbZd5_Ne_mefUGwJnk/gviz/tq?tqx=out:csv&sheet=PLAYERIDMAP"

credentials:
  bigquery: mlb-db-loader.json

constants:
  teams:
    - AZ
    - ATL
    - BAL
    - BOS
    - CHC
    - CIN
    - CLE
    - COL
    - CWS
    - DET
    - HOU
    - KC
    - LAA
    - LAD
    - MIA
    - MIL
    - MIN
    - NYM
    - NYY
    - OAK
    - PHI
    - PIT
    - SD
    - SEA
    - SF
    - STL
    - TB
    - TEX
    - TOR
    - WSH

bigquery:
  project_id: ad-fantasy-baseball
  dataset_id: core
  tables:
    statcast:
      name: statcast
      fields:
      - name: event_id
        type: STRING
        mode: NULLABLE
      - name: pitch_type
        type: STRING
        mode: NULLABLE
      - name: game_date
        type: DATE
        mode: NULLABLE
      - name: release_speed
        type: BIGNUMERIC
        mode: NULLABLE
      - name: release_pos_x
        type: BIGNUMERIC
        mode: NULLABLE
      - name: release_pos_z
        type: BIGNUMERIC
        mode: NULLABLE
      - name: player_name
        type: STRING
        mode: NULLABLE
      - name: batter
        type: STRING
        mode: NULLABLE
      - name: pitcher
        type: STRING
        mode: NULLABLE
      - name: events
        type: STRING
        mode: NULLABLE
      - name: description
        type: STRING
        mode: NULLABLE
      - name: spin_dir
        type: BIGNUMERIC
        mode: NULLABLE
      - name: spin_rate_deprecated
        type: BIGNUMERIC
        mode: NULLABLE
      - name: break_angle_deprecated
        type: BIGNUMERIC
        mode: NULLABLE
      - name: break_length_deprecated
        type: BIGNUMERIC
        mode: NULLABLE
      - name: zone
        type: INTEGER
        mode: NULLABLE
      - name: des
        type: STRING
        mode: NULLABLE
      - name: game_type
        type: STRING
        mode: NULLABLE
      - name: stand
        type: STRING
        mode: NULLABLE
      - name: p_throws
        type: STRING
        mode: NULLABLE
      - name: home_team
        type: STRING
        mode: NULLABLE
      - name: away_team
        type: STRING
        mode: NULLABLE
      - name: type
        type: STRING
        mode: NULLABLE
      - name: hit_location
        type: BIGNUMERIC
        mode: NULLABLE
      - name: bb_type
        type: STRING
        mode: NULLABLE
      - name: balls
        type: INTEGER
        mode: NULLABLE
      - name: strikes
        type: INTEGER
        mode: NULLABLE
      - name: game_year
        type: INTEGER
        mode: NULLABLE
      - name: pfx_x
        type: BIGNUMERIC
        mode: NULLABLE
      - name: pfx_z
        type: BIGNUMERIC
        mode: NULLABLE
      - name: plate_x
        type: BIGNUMERIC
        mode: NULLABLE
      - name: plate_z
        type: BIGNUMERIC
        mode: NULLABLE
      - name: on_3b
        type: STRING
        mode: NULLABLE
      - name: on_2b
        type: STRING
        mode: NULLABLE
      - name: on_1b
        type: STRING
        mode: NULLABLE
      - name: outs_when_up
        type: INTEGER
        mode: NULLABLE
      - name: inning
        type: INTEGER
        mode: NULLABLE
      - name: inning_topbot
        type: STRING
        mode: NULLABLE
      - name: hc_x
        type: BIGNUMERIC
        mode: NULLABLE
      - name: hc_y
        type: BIGNUMERIC
        mode: NULLABLE
      - name: tfs_deprecated
        type: BIGNUMERIC
        mode: NULLABLE
      - name: tfs_zulu_deprecated
        type: BIGNUMERIC
        mode: NULLABLE
      - name: umpire
        type: STRING
        mode: NULLABLE
      - name: sv_id
        type: STRING
        mode: NULLABLE
      - name: vx0
        type: BIGNUMERIC
        mode: NULLABLE
      - name: vy0
        type: BIGNUMERIC
        mode: NULLABLE
      - name: vz0
        type: BIGNUMERIC
        mode: NULLABLE
      - name: ax
        type: BIGNUMERIC
        mode: NULLABLE
      - name: ay
        type: BIGNUMERIC
        mode: NULLABLE
      - name: az
        type: BIGNUMERIC
        mode: NULLABLE
      - name: sz_top
        type: BIGNUMERIC
        mode: NULLABLE
      - name: sz_bot
        type: BIGNUMERIC
        mode: NULLABLE
      - name: hit_distance_sc
        type: BIGNUMERIC
        mode: NULLABLE
      - name: launch_speed
        type: BIGNUMERIC
        mode: NULLABLE
      - name: launch_angle
        type: BIGNUMERIC
        mode: NULLABLE
      - name: effective_speed
        type: BIGNUMERIC
        mode: NULLABLE
      - name: release_spin_rate
        type: BIGNUMERIC
        mode: NULLABLE
      - name: release_extension
        type: BIGNUMERIC
        mode: NULLABLE
      - name: game_pk
        type: STRING
        mode: NULLABLE
      - name: pos2_person_id
        type: STRING
        mode: NULLABLE
      - name: pos3_person_id
        type: STRING
        mode: NULLABLE
      - name: pos4_person_id
        type: STRING
        mode: NULLABLE
      - name: pos5_person_id
        type: STRING
        mode: NULLABLE
      - name: pos6_person_id
        type: STRING
        mode: NULLABLE
      - name: pos7_person_id
        type: STRING
        mode: NULLABLE
      - name: pos8_person_id
        type: STRING
        mode: NULLABLE
      - name: pos9_person_id
        type: STRING
        mode: NULLABLE
      - name: release_pos_y
        type: BIGNUMERIC
        mode: NULLABLE
      - name: estimated_ba_using_speedangle
        type: BIGNUMERIC
        mode: NULLABLE
      - name: estimated_woba_using_speedangle
        type: BIGNUMERIC
        mode: NULLABLE
      - name: woba_value
        type: BIGNUMERIC
        mode: NULLABLE
      - name: woba_denom
        type: BIGNUMERIC
        mode: NULLABLE
      - name: babip_value
        type: BIGNUMERIC
        mode: NULLABLE
      - name: iso_value
        type: BIGNUMERIC
        mode: NULLABLE
      - name: launch_speed_angle
        type: BIGNUMERIC
        mode: NULLABLE
      - name: at_bat_number
        type: INTEGER
        mode: NULLABLE
      - name: pitch_number
        type: INTEGER
        mode: NULLABLE
      - name: pitch_name
        type: STRING
        mode: NULLABLE
      - name: home_score
        type: INTEGER
        mode: NULLABLE
      - name: away_score
        type: INTEGER
        mode: NULLABLE
      - name: bat_score
        type: INTEGER
        mode: NULLABLE
      - name: fld_score
        type: INTEGER
        mode: NULLABLE
      - name: post_away_score
        type: INTEGER
        mode: NULLABLE
      - name: post_home_score
        type: INTEGER
        mode: NULLABLE
      - name: post_bat_score
        type: INTEGER
        mode: NULLABLE
      - name: post_fld_score
        type: INTEGER
        mode: NULLABLE
      - name: if_fielding_alignment
        type: STRING
        mode: NULLABLE
      - name: of_fielding_alignment
        type: STRING
        mode: NULLABLE
      - name: delta_home_win_exp
        type: BIGNUMERIC
        mode: NULLABLE
      - name: delta_run_exp
        type: BIGNUMERIC
        mode: NULLABLE
      - name: bat_speed
        type: BIGNUMERIC
        mode: NULLABLE
      - name: swing_length
        type: BIGNUMERIC
        mode: NULLABLE
      - name: estimated_slg_using_speedangle
        type: NUMERIC
        mode: nullable
      - name: delta_pitcher_run_exp
        type: NUMERIC
        mode: nullable
      - name: hyper_speed
        type: NUMERIC
        mode: nullable
      - name: home_score_diff
        type: INTEGER
        mode: nullable
      - name: bat_score_diff
        type: INTEGER
        mode: nullable
      - name: home_win_exp
        type: NUMERIC
        mode: nullable
      - name: bat_win_exp
        type: NUMERIC
        mode: nullable
      - name: age_pit_legacy
        type: INTEGER
        mode: nullable
      - name: age_bat_legacy
        type: INTEGER
        mode: nullable
      - name: age_pit
        type: INTEGER
        mode: nullable
      - name: age_bat
        type: INTEGER
        mode: nullable
      - name: n_thruorder_pitcher
        type: INTEGER
        mode: nullable
      - name: n_priorpa_thisgame_player_at_bat
        type: INTEGER
        mode: nullable
      - name: pitcher_days_since_prev_game
        type: INTEGER
        mode: nullable
      - name: batter_days_since_prev_game
        type: INTEGER
        mode: nullable
      - name: pitcher_days_until_next_game
        type: INTEGER
        mode: nullable
      - name: batter_days_until_next_game
        type: INTEGER
        mode: nullable
      - name: api_break_z_with_gravity
        type: NUMERIC
        mode: nullable
      - name: api_break_x_arm
        type: NUMERIC
        mode: nullable
      - name: api_break_x_batter_in
        type: NUMERIC
        mode: nullable
      - name: arm_angle
        type: NUMERIC
        mode: nullable
      - name: attack_angle
        type: NUMERIC
        mode: nullable
      - name: attack_direction
        type: NUMERIC
        mode: nullable
      - name: swing_path_tilt
        type: NUMERIC
        mode: nullable
      - name: intercept_ball_minus_batter_pos_x_inches
        type: NUMERIC
        mode: nullable
      - name: intercept_ball_minus_batter_pos_y_inches
        type: NUMERIC
        mode: nullable
      - name: load_time
        type: DATETIME
        mode: NULLABLE
    players:
      name: players
      fields:
      - name: IDPLAYER
        type: STRING
        mode: NULLABLE
      - name: PLAYERNAME
        type: STRING
        mode: NULLABLE
      - name: BIRTHDATE
        type: STRING
        mode: NULLABLE
      - name: FIRSTNAME
        type: STRING
        mode: NULLABLE
      - name: LASTNAME
        type: STRING
        mode: NULLABLE
      - name: TEAM
        type: STRING
        mode: NULLABLE
      - name: LG
        type: STRING
        mode: NULLABLE
      - name: POS
        type: STRING
        mode: NULLABLE
      - name: IDFANGRAPHS
        type: STRING
        mode: NULLABLE
      - name: FANGRAPHSNAME
        type: STRING
        mode: NULLABLE
      - name: MLBID
        type: STRING
        mode: NULLABLE
      - name: MLBNAME
        type: STRING
        mode: NULLABLE
      - name: CBSID
        type: STRING
        mode: NULLABLE
      - name: CBSNAME
        type: STRING
        mode: NULLABLE
      - name: RETROID
        type: STRING
        mode: NULLABLE
      - name: BREFID
        type: STRING
        mode: NULLABLE
      - name: NFBCID
        type: STRING
        mode: NULLABLE
      - name: NFBCNAME
        type: STRING
        mode: NULLABLE
      - name: ESPNID
        type: STRING
        mode: NULLABLE
      - name: ESPNNAME
        type: STRING
        mode: NULLABLE
      - name: KFFLNAME
        type: STRING
        mode: NULLABLE
      - name: DAVENPORTID
        type: STRING
        mode: NULLABLE
      - name: BPID
        type: STRING
        mode: NULLABLE
      - name: YAHOOID
        type: STRING
        mode: NULLABLE
      - name: YAHOONAME
        type: STRING
        mode: NULLABLE
      - name: MSTRBLLNAME
        type: STRING
        mode: NULLABLE
      - name: BATS
        type: STRING
        mode: NULLABLE
      - name: THROWS
        type: STRING
        mode: NULLABLE
      - name: FANTPROSNAME
        type: STRING
        mode: NULLABLE
      - name: LASTCOMMAFIRST
        type: STRING
        mode: NULLABLE
      - name: ROTOWIREID
        type: STRING
        mode: NULLABLE
      - name: FANDUELNAME
        type: STRING
        mode: NULLABLE
      - name: FANDUELID
        type: STRING
        mode: NULLABLE
      - name: DRAFTKINGSNAME
        type: STRING
        mode: NULLABLE
      - name: OTTONEUID
        type: STRING
        mode: NULLABLE
      - name: HQID
        type: STRING
        mode: NULLABLE
      - name: RAZZBALLNAME
        type: STRING
        mode: NULLABLE
      - name: FANTRAXID
        type: STRING
        mode: NULLABLE
      - name: FANTRAXNAME
        type: STRING
        mode: NULLABLE
      - name: ROTOWIRENAME
        type: STRING
        mode: NULLABLE
      - name: ALLPOS
        type: STRING
        mode: NULLABLE
      - name: NFBCLASTFIRST
        type: STRING
        mode: NULLABLE
      - name: ACTIVE
        type: STRING
        mode: NULLABLE
      - name: UNDERDOG
        type: STRING
        mode: NULLABLE
      - name: RAZZBALLID
        type: STRING
        mode: NULLABLE
