database:
  host: localhost
  username: mlb-db
  password: password
  db: mlbdb
  statcast_table: statcast
  players_table: players

api:
  statcast: 'https://baseballsavant.mlb.com/statcast_search/csv?all=true&hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=&hfC=&hfSea={year}%7C&hfSit=&player_type=pitcher&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=&game_date_lt=&team={team}&position=&hfRO=&home_road=&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name-event&sort_col=pitches&player_event_sort=api_p_release_speed&sort_order=desc&min_abs=0&type=details&'
  players: 'http://crunchtimebaseball.com/master.csv'
  players_historical: 'http://www.baseballprospectus.com/sortable/playerids/playerid_list.csv'
