[project]
name = "mlb-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy==1.26.4",
    "pandas==2.3.1",
    "pandas-gbq==0.29.2",
    "pyyaml==6.0.1",
]
