CREATE TABLE IF NOT EXISTS `statcast` (
  `event_id` varchar(255),
  `pitch_type` varchar(255) DEFAULT NULL,
  `game_date` DATE DEFAULT NULL,
  `release_speed` decimal(10,6) DEFAULT NULL,
  `release_pos_x` decimal(10,6) DEFAULT NULL,
  `release_pos_z` decimal(10,6) DEFAULT NULL,
  `player_name` varchar(255) DEFAULT NULL,
  `batter` varchar(255) DEFAULT NULL,
  `pitcher` varchar(255) DEFAULT NULL,
  `events` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `spin_dir` varchar(255) DEFAULT NULL,
  `spin_rate_deprecated` varchar(255) DEFAULT NULL,
  `break_angle_deprecated` varchar(255) DEFAULT NULL,
  `break_length_deprecated` varchar(255) DEFAULT NULL,
  `zone` tinyint DEFAULT NULL,
  `des` text DEFAULT NULL,
  `game_type` varchar(255) DEFAULT NULL,
  `stand` varchar(255) DEFAULT NULL,
  `p_throws` varchar(255) DEFAULT NULL,
  `home_team` varchar(255) DEFAULT NULL,
  `away_team` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `hit_location` tinyint DEFAULT NULL,
  `bb_type` varchar(255) DEFAULT NULL,
  `balls` tinyint DEFAULT NULL,
  `strikes` tinyint DEFAULT NULL,
  `game_year` year DEFAULT NULL,
  `pfx_x` decimal(10,6) DEFAULT NULL,
  `pfx_z` decimal(10,6) DEFAULT NULL,
  `plate_x` decimal(10,6) DEFAULT NULL,
  `plate_z` decimal(10,6) DEFAULT NULL,
  `on_3b` varchar(255) DEFAULT NULL,
  `on_2b` varchar(255) DEFAULT NULL,
  `on_1b` varchar(255) DEFAULT NULL,
  `outs_when_up` tinyint DEFAULT NULL,
  `inning` tinyint DEFAULT NULL,
  `inning_topbot` varchar(255) DEFAULT NULL,
  `hc_x` decimal(10,6) DEFAULT NULL,
  `hc_y` decimal(10,6) DEFAULT NULL,
  `tfs_deprecated` varchar(255) DEFAULT NULL,
  `tfs_zulu_deprecated` varchar(255) DEFAULT NULL,
  `umpire` varchar(255) DEFAULT NULL,
  `sv_id` varchar(255),
  `vx0` decimal(10,6) DEFAULT NULL,
  `vy0` decimal(10,6) DEFAULT NULL,
  `vz0` decimal(10,6) DEFAULT NULL,
  `ax` decimal(10,6) DEFAULT NULL,
  `ay` decimal(10,6) DEFAULT NULL,
  `az` decimal(10,6) DEFAULT NULL,
  `sz_top` decimal(10,6) DEFAULT NULL,
  `sz_bot` decimal(10,6) DEFAULT NULL,
  `hit_distance_sc` smallint DEFAULT NULL,
  `launch_speed` decimal(10,6) DEFAULT NULL,
  `launch_angle` decimal(10,6) DEFAULT NULL,
  `effective_speed` decimal(10,6) DEFAULT NULL,
  `release_spin_rate` smallint DEFAULT NULL,
  `release_extension` decimal(10,6) DEFAULT NULL,
  `game_pk` varchar(255) DEFAULT NULL,
  `pos1_person_id` varchar(255) DEFAULT NULL,
  `pos2_person_id` varchar(255) DEFAULT NULL,
  `pos3_person_id` varchar(255) DEFAULT NULL,
  `pos4_person_id` varchar(255) DEFAULT NULL,
  `pos5_person_id` varchar(255) DEFAULT NULL,
  `pos6_person_id` varchar(255) DEFAULT NULL,
  `pos7_person_id` varchar(255) DEFAULT NULL,
  `pos8_person_id` varchar(255) DEFAULT NULL,
  `pos9_person_id` varchar(255) DEFAULT NULL,
  `release_pos_y` decimal(10,6) DEFAULT NULL,
  `estimated_ba_using_speedangle` decimal(10,6) DEFAULT NULL,
  `estimated_woba_using_speedangle` decimal(10,6) DEFAULT NULL,
  `woba_value` decimal(10,6) DEFAULT NULL,
  `woba_denom` tinyint DEFAULT NULL,
  `babip_value` tinyint DEFAULT NULL,
  `iso_value` tinyint DEFAULT NULL,
  `launch_speed_angle` tinyint DEFAULT NULL,
  `at_bat_number` smallint DEFAULT NULL,
  `pitch_number` tinyint DEFAULT NULL,
  `pitch_name` varchar(255) DEFAULT NULL,
  `home_score` tinyint DEFAULT NULL,
  `away_score` tinyint DEFAULT NULL,
  `bat_score` tinyint DEFAULT NULL,
  `fld_score` tinyint DEFAULT NULL,
  `post_away_score` tinyint DEFAULT NULL,
  `post_home_score` tinyint DEFAULT NULL,
  `post_bat_score` tinyint DEFAULT NULL,
  `post_fld_score` tinyint DEFAULT NULL,
  PRIMARY KEY (`event_id`),
  KEY `index_sv_id` (`sv_id`),
  KEY `index_batter` (`batter`),
  KEY `index_pitcher` (`pitcher`),
  KEY `index_game_pk` (`game_pk`),
  KEY `index_game_year` (`game_year`),
  KEY `index_game_date` (`game_date`)
) ENGINE=InnoDB CHARSET=utf8
;

CREATE TABLE IF NOT EXISTS `players` (
  `mlb_id` varchar(255),
  `mlb_name` varchar(255) DEFAULT NULL,
  `mlb_pos` varchar(255) DEFAULT NULL,
  `mlb_team` varchar(255) DEFAULT NULL,
  `mlb_team_long` varchar(255) DEFAULT NULL,
  `bats` varchar(255) DEFAULT NULL,
  `throws` varchar(255) DEFAULT NULL,
  `birth_year` year DEFAULT NULL,
  `bp_id` varchar(255) DEFAULT NULL,
  `bref_id` varchar(255) DEFAULT NULL,
  `bref_name` varchar(255) DEFAULT NULL,
  `cbs_id` varchar(255) DEFAULT NULL,
  `cbs_name` varchar(255) DEFAULT NULL,
  `cbs_pos` varchar(255) DEFAULT NULL,
  `espn_id` varchar(255) DEFAULT NULL,
  `espn_name` varchar(255) DEFAULT NULL,
  `espn_pos` varchar(255) DEFAULT NULL,
  `fg_id` varchar(255) DEFAULT NULL,
  `fg_name` varchar(255) DEFAULT NULL,
  `fg_pos` varchar(255) DEFAULT NULL,
  `lahman_id` varchar(255) DEFAULT NULL,
  `nfbc_id` varchar(255) DEFAULT NULL,
  `nfbc_name` varchar(255) DEFAULT NULL,
  `nfbc_pos` varchar(255) DEFAULT NULL,
  `retro_id` varchar(255) DEFAULT NULL,
  `retro_name` varchar(255) DEFAULT NULL,
  `debut` varchar(255) DEFAULT NULL,
  `yahoo_id` varchar(255) DEFAULT NULL,
  `yahoo_name` varchar(255) DEFAULT NULL,
  `yahoo_pos` varchar(255) DEFAULT NULL,
  `mlb_depth` varchar(255) DEFAULT NULL,
  `ottoneu_id` varchar(255) DEFAULT NULL,
  `ottoneu_name` varchar(255) DEFAULT NULL,
  `ottoneu_pos` varchar(255) DEFAULT NULL,
  `rotowire_id` varchar(255) DEFAULT NULL,
  `rotowire_name` varchar(255) DEFAULT NULL,
  `rotowire_pos` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`mlb_id`),
  KEY `index_bp_id` (`bp_id`),
  KEY `index_cbs_id` (`cbs_id`),
  KEY `index_espn_id` (`espn_id`),
  KEY `index_fg_id` (`fg_id`),
  KEY `index_lahman_id` (`lahman_id`),
  KEY `index_nfbc_id` (`nfbc_id`),
  KEY `index_retro_id` (`retro_id`),
  KEY `index_yahoo_id` (`yahoo_id`),
  KEY `index_ottoneu_id` (`ottoneu_id`),
  KEY `index_rotowire_id` (`rotowire_id`)
) ENGINE=InnoDB CHARSET=utf8
;
